[project]
name = "paper-searcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arxiv>=2.4.0",
    "streamlit>=1.52.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.11",
]
